# This file was generated by the Rust Makefile Generator

all: out out/test.o out/test2.o
	gcc out/test.o out/test2.o

out/test.o: out test.c
	 gcc test.c -o out/test.o

out/test2.o: out test2.c
	 gcc test2.c -o out/test2.o

out:
	mkdir out

clean:
	rm -rf out

run: all
	./a.out

.PHONY: all clean run